# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true

apt_packages:
  - libgsl0-dbg
  - libgsl0-dev
  - libgsl0ldbl
  - libcurl4-openssl-dev
  - libxml2-dev

r_binary_packages:
  - kdevine
