# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true

apt_packages:
  - libgsl0-dbg
  - libgsl0-dev
  - libgsl0ldbl
  - libcurl4-openssl-dev
  - libxml2-dev

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-5 g++-5 gfortran-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 100
  - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-5 100

