# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fit_margins_cpp <- function(data, nlevels, mult, xmin, xmax, bw, deg, weights, num_threads) {
    .Call(`_vinereg_fit_margins_cpp`, data, nlevels, mult, xmin, xmax, bw, deg, weights, num_threads)
}

select_dvine_cpp <- function(data, family_set, par_method, nonpar_method, mult, selcrit, weights, psi0, preselect_families, cores, var_types) {
    .Call(`_vinereg_select_dvine_cpp`, data, family_set, par_method, nonpar_method, mult, selcrit, weights, psi0, preselect_families, cores, var_types)
}

cond_quantile_cpp <- function(alpha, u, vinecop_r, num_threads) {
    .Call(`_vinereg_cond_quantile_cpp`, alpha, u, vinecop_r, num_threads)
}

cond_dist_cpp <- function(u, vinecop_r, num_threads) {
    .Call(`_vinereg_cond_dist_cpp`, u, vinecop_r, num_threads)
}

