# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

select_dvine_cpp <- function(data, var_types) {
    .Call(`_vinereg_select_dvine_cpp`, data, var_types)
}

cond_quantile_cpp <- function(alpha, u, vinecop_r, num_threads) {
    .Call(`_vinereg_cond_quantile_cpp`, alpha, u, vinecop_r, num_threads)
}

cond_dist_cpp <- function(u, vinecop_r, num_threads) {
    .Call(`_vinereg_cond_dist_cpp`, u, vinecop_r, num_threads)
}

